fixtures:
  symlinks:
    grafana: "#{source_dir}"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.5.1"
    docker_systemd:
      repo: "ajsmith/docker_systemd"
      ref:  "0.2.3"
