fixtures:
  symlinks:
    grafana: "#{source_dir}"
  forge_modules:
    bundler:
      repo: "ploperations/bundler"
      ref:  "1.0.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.5.1"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref:  "1.3.1"
