name    'ajsmith-grafana'
version '0.3.0'
source 'UNKNOWN'
author 'Alex Smith <alex.smith@redhat.com>'
license 'GPL-2'
summary 'Grafana application configuration.'
description ''

dependency 'puppetlabs/stdlib', '>=4.5.1'
dependency 'puppetlabs/docker_platform', '>=1.1.0'
dependency 'puppetlabs/vcsrepo', '>=1.3.1'
